/*
 * Written by Bastien Chevreux (BaCh)
 *
 * Copyright (C) 1997-2000 by the German Cancer Research Center (Deutsches
 *   Krebsforschungszentrum, DKFZ Heidelberg) and Bastien Chevreux
 * Copyright (C) 2000 and later by Bastien Chevreux
 *
 * All rights reserved.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the
 * Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA
 *
 */

#ifndef _mira_enums_h_
#define _mira_enums_h_

//enum loadjob {LOAD_FOFNEXP=0, LOAD_FASTA, LOAD_CAF, LOAD_PHD, LOAD_FOFNPHD, LOAD_GBF, LOAD_NONE};
enum analysejob {ANALYSE_NONE=0, ANALYSE_TEXT, ANALYSE_SIGNAL};
enum externalqual {E_QUAL_NONE=0, E_QUAL_SCF};
enum extendreads {EXTEND_NONE=0, EXTEND_BOLD};



#endif


// Local Variables:
// mode: C++
// End:
